services:
  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine

  backend:
    build: .
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - DJANGO_TIME_ZONE=${DJANGO_TIME_ZONE}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db
      - redis

  celery_worker:
    build: .
    command: celery -A core worker -l INFO
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - DJANGO_TIME_ZONE=${DJANGO_TIME_ZONE}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - backend

  celery_beat:
    build: .
    command: celery -A core beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - DJANGO_TIME_ZONE=${DJANGO_TIME_ZONE}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - backend
  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    command: python main.py
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - API_BASE_URL=http://backend:8000/api/v1
      - REDIS_URL_FOR_BOT=redis://redis:6379/1
    ports:
      - "8080:8080"
    depends_on:
      - backend

volumes:
  postgres_data: